server {
    listen 80;
    server_name localhost;

    root /usr/share/nginx/html;
    index index.html;

    # Necessário para o React Router funcionar — redireciona tudo para index.html
    location / {
        try_files $uri $uri/ /index.html;
    }
}