services:

  mongo:
    image: mongo:7
    container_name: mongo
    restart: unless-stopped
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db
    networks:
      - api_net

  api:
    build: .
    container_name: api
    restart: unless-stopped
    ports:
      - "3000:3000"
    env_file:
      - .env
    depends_on:
      - mongo
    volumes:
      - sqlite_data:/data
    networks:
      - api_net

  test:
    build:
      context: .
      dockerfile: Dockerfile.test
    container_name: api_test
    env_file:
      - .env
    environment:
      MONGO_URI_TEST: mongodb://mongo:27017/api_test
    depends_on:
      - mongo
    networks:
      - api_net
    profiles:
      - test

volumes:
  mongo_data:
  sqlite_data:

networks:
  api_net:
    driver: bridge